# Generated by Django 5.2.6 on 2025-11-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_cruise_inforequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='inforequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inforequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='inforequest',
            name='message',
        ),
        migrations.AddField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='cruises', to='relecloud.destination'),
        ),
        migrations.AddField(
            model_name='inforequest',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inforequest',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='cruise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relecloud.cruise'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
